services:
  # La web API (Node.js)
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    labels:
      - "autoheal=true"
    container_name: ${PROJECT_NAME}-api
    ports:
      - "${HOST_PORT_API}:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "mysqladmin", "-hdb", "-P3306", "ping", "--silent"]
      interval: 10s
      timeout: 10s
      retries: 10
    command: ["npx", "nodemon", "./bin/www"]

  # La base de données MySQL
  db:
    image: mysql:8
    restart: always
    labels:
      - "autoheal=true"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - ./dbdata:/var/lib/mysql
    ports:
      - "${HOST_PORT_DB}:3306"
    container_name: ${PROJECT_NAME}-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 5

  # L'interface Adminer pour gérer la base de données
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    container_name: ${PROJECT_NAME}-adminer
    ports:
      - "${HOST_PORT_ADMINER}:8080"
